project_id = "simpawfglbrdvtixkaxq"

[functions.nyayscan]
verify_jwt = false

[functions.nyayscan-detailed]
verify_jwt = false

[functions.nyaymail]
verify_jwt = false

[functions.nyaynotice]
verify_jwt = false

[functions.snehh-chat]
verify_jwt = false

[functions.generate-case-summary]
verify_jwt = false

[functions.nyaymail-reply]
verify_jwt = false

[functions.lawyer-chat-ai]
verify_jwt = false
